apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-key-manager.api.fullname" . }}
  labels:
    {{- include "api-key-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
stringData:
  DATABASE_URL: {{ include "api-key-manager.postgresql.connectionString" . | quote }}
  KEY_PEPPER: {{ .Values.api.keyPepper | quote }}
