{{ $fullName := printf "%s-proxy" (include "image-storage-service.prefix" .) | trunc 63 | trimSuffix "-"  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullName }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      containers:
      - name: {{ $fullName }}
        image: moreillon/api-proxy:ebc18c41
        ports:
        - containerPort: 80
        env:
        - name: PATH_PREFIX
          value: ""
        - name: PROXY_API
          value: http://{{ printf "%s-back" (include "image-storage-service.prefix" .) | trunc 63 | trimSuffix "-" }}
        - name: PROXY_ROOT
          value: http://{{ printf "%s-gui" (include "image-storage-service.prefix" .) | trunc 63 | trimSuffix "-" }}
        {{ if .Values.auth.enabled }}
        - name: PROXY_AUTH
          value: http://{{ printf "%s-auth-api" .Release.Name | trunc 63 | trimSuffix "-" }}
        {{ end }}
