apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "image-storage-service.prefix" .}}-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{include "image-storage-service.prefix" .}}-proxy
  template:
    metadata:
      labels:
        app: {{include "image-storage-service.prefix" .}}-proxy
    spec:
      containers:
      - name: {{include "image-storage-service.prefix" .}}-proxy
        image: moreillon/api-proxy:a3e8b41e
        ports:
        - containerPort: 80
        env:
        - name: PROXY_BACK
          value: http://{{include "image-storage-service.prefix" .}}-back
        - name: PROXY_ROOT
          value: http://{{include "image-storage-service.prefix" .}}-gui
