apiVersion: v2
name: image-storage-service
description: Helm chart for the Image Storage Service

type: application

version: 0.2.28

appVersion: "v1.16.9"

icon: https://raw.githubusercontent.com/jtekt/helm-repository/master/charts/image-storage-service/icon.png

dependencies:
  - name: mongodb
    version: 13.18.5
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: user-manager-mongodb
    version: 0.3.5
    repository: https://maximemoreillon.github.io/helm-repository
    condition: auth.enabled
    alias: auth
