pvc_sizes:
  mongo: 100Gi
  imageStorage: 200Gi

ports:
  backEnd: 30170
  frontEnd: 30180

ingress:
  enabled: false
  #host: images.example.com
  #annotations:
  #  kubernetes.io/ingress.class: nginx
  #  cert-manager.io/cluster-issuer: letsencrypt-prod
