nameOverride: iss

image: public.ecr.aws/jtekt-corporation/image-storage-service:v1.16.9

gui:
  image: public.ecr.aws/jtekt-corporation/image-storage-service-gui:v1.6.1

service:
  type: NodePort
  nodePort: 32101

persistence:
  size: 100Gi

ingress:
  enabled: false
  #host: images.example.com
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

mongodb:
  enabled: true
  persistence:
    size: 100Gi
  auth:
    enabled: false
    rootPassword: banana

auth:
  enabled: false
  mongodb:
    enabled: false
