nameOverride: iss
# TODO: rename to service.nodePorts
service:
  nodePorts:
    api: 30170
    gui: 30180

persistence:
  sieze: 100Gi

ingress:
  enabled: false
  #host: images.example.com
  #annotations:
  #  kubernetes.io/ingress.class: nginx
  #  cert-manager.io/cluster-issuer: letsencrypt-prod

mongodb:
  enabled: true
  persistence:
    size: 100Gi
  auth:
    enabled: false
    rootPassword: banana

auth:
  enabled: false
  mongodb:
    enabled: false
