# nameOverride: iss

image: public.ecr.aws/jtekt-corporation/image-storage-service:v1.16.9

gui:
  image: public.ecr.aws/jtekt-corporation/image-storage-service-gui:v1.8.2

persistence:
  size: 20Gi

mongodb:
  enabled: true
  arbiter:
    enabled: false
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  persistence:
    size: 10Gi
  auth:
    enabled: false
    rootPassword: banana

auth:
  enabled: false
  mongodb:
    enabled: false

kong:
  admin:
    enabled: false # Do not create a service for the admin API
  manager:
    enabled: false # Do not create a service for Kong Manager
  ingressController:
    enabled: false
  env:
    database: "off"
    dns_order: A,CNAME,LAST,SRV
  dblessConfig:
    configMap: kong-config
  proxy:
    type: NodePort
    http:
      nodePort: 30107
    tls:
      enabled: false
