apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-proxy
spec:
  type: NodePort
  selector:
    app: {{ .Values.applicationName }}-proxy
  ports:
  - port: 80
    nodePort: {{ .Values.ports.frontEnd}}