apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-key-manager.proxy.fullname" . }}
  labels:
    {{- include "api-key-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  type: {{ .Values.proxy.service.type }}
  selector:
    {{- include "api-key-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.proxy.service.type "NodePort") .Values.proxy.service.nodePort }}
      nodePort: {{ .Values.proxy.service.nodePort }}
      {{- end }}
