apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-image-storage-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-image-storage-front
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-image-storage-front
    spec:
      containers:
      - name: {{ .Release.Name }}-image-storage-front
        image: public.ecr.aws/u6l4m3e5/image-storage-service-gui:b3b16dbb
        ports:
        - containerPort: 80
        env:
        - name: VUE_APP_IMAGE_STORAGE_API_URL
          value: /proxy/api
