# Default values for shinsei-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



adminAccount:
  username: admin
  password: admin

token_secret: keyboardcat

ports:
  shinseiManagerGui: 30018
  groupManager: 30019
  userManager: 30020

storage:
  neo4j: 100Gi
  shinseiManager: 100Gi


neo4j:
  enabled: true
  nameOverride: neo4j
  neo4j:
    name: neo4j
    password: neo4Jpassword
    acceptLicenseAgreement: "yes"
  volumes:
    data:
      mode: defaultStorageClass