stages:
  - release

image: moreillon/ci-dind:v1.0.3
services:
  - name: docker:24.0.7-dind

release-job:
  stage: release
  only:
    - master
  tags:
    - internal-dind
  script:
    - bash release.sh
