{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-key-manager.postgresql.fullname" . }}
  labels:
    {{- include "api-key-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  selector:
    {{- include "api-key-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
{{- end }}
