apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-key-manager.gui.fullname" . }}
  labels:
    {{- include "api-key-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: gui
spec:
  type: ClusterIP
  selector:
    {{- include "api-key-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gui
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
