apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shinsei-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.shinseiManager }}
