{{- $fullName := include "shinsei-manager.prefix" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "shinsei-manager.labels" . | nindent 4 }}
    app: {{ $fullName }}
spec:
  type: ClusterIP
  selector:
    app: {{ $fullName }}
  ports:
  - port: 80
