{{- $fullName := printf "%s-front" (include "shinsei-manager.prefix" .) | trunc 63 | trimSuffix "-" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "shinsei-manager.labels" . | nindent 4 }}
    app: {{ $fullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullName }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      containers:
      - name: {{ $fullName }}
        image: {{ .Values.images.shinseiManager.gui }}
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: {{ include "shinsei-manager.prefix" . }}-env
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
