apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinsei-manager-api-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shinsei-manager-api-proxy
  template:
    metadata:
      labels:
        app: shinsei-manager-api-proxy
    spec:
      containers:
      - name: shinsei-manager-api-proxy
        image: moreillon/api-proxy
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
           name: environment-variables
        env:
        - name: PROXY_ROOT
          value: http://shinsei-manager-front
        - name: PROXY_API
          value: http://shinsei-manager-api
        - name: PROXY_AUTH
          value: http://user-manager-api
