apiVersion: v1
kind: Service
metadata:
  name: shinsei-manager-api-proxy
spec:
  type: NodePort
  selector:
    app: shinsei-manager-api-proxy
  ports:
  - port: 80
    nodePort: {{ .Values.ports.shinseiManager }}
