{{- $fullName := include "shinsei-manager.prefix" . }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "shinsei-manager.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.shinseiManager }}
