apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "image-storage-service.gui.fullname" . }}
  labels:
    {{- include "image-storage-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: gui
spec:
  replicas: {{ .Values.gui.replicaCount }}
  selector:
    matchLabels:
      {{- include "image-storage-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gui
  template:
    metadata:
      labels:
        {{- include "image-storage-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gui
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gui
          image: {{ .Values.gui.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: VUE_APP_IMAGE_STORAGE_API_URL
              value: /api
            {{- if .Values.auth.enabled }}
            - name: VUE_APP_IDENTIFICATION_URL
              value: /auth/users/self
            - name: VUE_APP_LOGIN_URL
              value: /auth/auth/login
            {{- end }}
          {{- with .Values.gui.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
