{{ $fullName := printf "%s-gui" (include "image-storage-service.prefix" .) | trunc 63 | trunc 63 | trimSuffix "-" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "image-storage-service.prefix" .}}-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{include "image-storage-service.prefix" .}}-gui
  template:
    metadata:
      labels:
        app: {{include "image-storage-service.prefix" .}}-gui
    spec:
      containers:
      - name: {{include "image-storage-service.prefix" .}}-gui
        image: {{ .Values.gui.image }}
        ports:
        - containerPort: 80
        env:
        - name: VUE_APP_IMAGE_STORAGE_API_URL
          value: /api
        {{ if .Values.auth.enabled }}
        - name: VUE_APP_IDENTIFICATION_URL
          value: /auth/users/self
        - name: VUE_APP_LOGIN_URL
          value: /auth/auth/login
        {{ end }}
