apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "image-storage-service.prefix" .}}-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{include "image-storage-service.prefix" .}}-gui
  template:
    metadata:
      labels:
        app: {{include "image-storage-service.prefix" .}}-gui
    spec:
      containers:
      - name: {{include "image-storage-service.prefix" .}}-gui
        image: public.ecr.aws/jtekt-corporation/image-storage-service-gui:0d08f660
        ports:
        - containerPort: 80
        env:
        - name: VUE_APP_IMAGE_STORAGE_API_URL
          value: /proxy/back
