apiVersion: v1
kind: Secret
metadata:
  name: environment-variables
type: Opaque
stringData:

  # Security
  JWT_SECRET: {{ .Values.token_secret }}

  # Databases
  ## Neo4j
  NEO4J_URL: bolt://neo4j
  NEO4J_USERNAME: {{ .Values.neo4j.username }}
  NEO4J_PASSWORD: {{ .Values.neo4j.password }}

  # Back-end variables
  IDENTIFICATION_URL: http://employee-manager/v2/users/self

  # Vue variables
  VUE_APP_SHINSEI_MANAGER_URL: /proxy/shinsei-manager
  VUE_APP_EMPLOYEE_MANAGER_API_URL: /proxy/employee-manager
  VUE_APP_GROUP_MANAGER_API_URL: /proxy/group-manager

  # Proxy
  PROXY_SHINSEI_MANAGER: http://shinsei-manager
  PROXY_GROUP_MANAGER: http://group-manager
  PROXY_EMPLOYEE_MANAGER: http://employee-manager
