apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      containers:
      - name: {{ .Release.Name }}-mongo
        image: mongo:4
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: "/data/db"
          name: {{ .Release.Name }}-mongo
      volumes:
      - name: {{ .Release.Name }}-mongo
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mongo
