apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "100Gi" .Values.pvc_sizes.mongo }}
