apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-back
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-back
    spec:
      containers:
      - name: {{ .Release.Name }}-back
        image: public.ecr.aws/u6l4m3e5/image-storage-service:067099d5
        ports:
        - containerPort: 80
        env:
        - name: MONGODB_URL
          value: mongodb://{{ .Release.Name }}-mongo
        volumeMounts:
        - mountPath: "/usr/share/pv"
          name: {{ .Release.Name }}-back
      volumes:
      - name: {{ .Release.Name }}-back
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-back
