apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-back
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-back
  ports:
  - port: 80
    nodePort: {{ .Values.ports.backEnd}}
