apiVersion: v1
kind: Service
metadata:
  name: user-manager-api-proxy
spec:
  type: NodePort
  selector:
    app: user-manager-api-proxy
  ports:
    - port: 80
      nodePort: {{ .Values.ports.userManager }}
