apiVersion: v1
kind: Service
metadata:
  name: {{ include "time-series-storage.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      {{ if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "time-series-storage.fullname" . }}