apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-manager
  template:
    metadata:
      labels:
        app: employee-manager
    spec:
      containers:
      - name: employee-manager
        image: moreillon/employee-manager:f0b062ac
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
           name: environment-variables
