apiVersion: v1
kind: Service
metadata:
  name: employee-manager-api-proxy
spec:
  type: NodePort
  selector:
    app: employee-manager-api-proxy
  ports:
  - port: 80
    nodePort: {{ .Values.ports.employeeManager }}
