apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manager-front
  template:
    metadata:
      labels:
        app: user-manager-front
    spec:
      containers:
        - name: user-manager-front
          image: moreillon/user-manager-front:v5.0.3
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: environment-variables
