apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-image-storage-front
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-image-storage-front
  ports:
  - port: 80
