{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "image-storage-service.prefix" . }}-api
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
    - hosts:
        - api.{{ include "image-storage-service.ingress.host" . }}
      secretName: {{ include "image-storage-service.prefix" . }}-api
  rules:
    - host: api.{{ include "image-storage-service.ingress.host" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: {{ include "image-storage-service.prefix" . }}-api
                port:
                  number: 80
{{- end }}
