apiVersion: v1
kind: Service
metadata:
  name: {{include "image-storage-service.prefix" .}}-gui
spec:
  type: ClusterIP
  selector:
    app: {{include "image-storage-service.prefix" .}}-gui
  ports:
  - port: 80
