apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{include "image-storage-service.prefix" .}}-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "100Gi" .Values.pvc_sizes.mongo }}
