{{ $mongodbUrl := include "image-storage-service.mongodb.url" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "image-storage-service.prefix" .}}-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{include "image-storage-service.prefix" .}}-back
  template:
    metadata:
      labels:
        app: {{include "image-storage-service.prefix" .}}-back
    spec:
      containers:
      - name: {{include "image-storage-service.prefix" .}}-back
        image: public.ecr.aws/jtekt-corporation/image-storage-service:6ee19653
        ports:
        - containerPort: 80
        env:
        - name: MONGODB_URL
          value: {{ $mongodbUrl }}
        volumeMounts:
        - mountPath: /usr/src/app/uploads
          name: {{include "image-storage-service.prefix" .}}-back
      volumes:
      - name: {{include "image-storage-service.prefix" .}}-back
        persistentVolumeClaim:
          claimName: {{include "image-storage-service.prefix" .}}-back
