{{ $fullName := printf "%s-api" (include "image-storage-service.prefix" .) | trunc 63 | trimSuffix "-" }}
{{ $mongodbConnectionString := include "image-storage-service.mongodb.connectionString" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullName }}
  template:
    metadata:
      labels:
        app: {{ $fullName }}
    spec:
      containers:
      - name: {{ $fullName }}
        image: {{ .Values.image }}
        env:
        - name: MONGODB_CONNECTION_STRING
          value: {{ $mongodbConnectionString }}
        {{ if .Values.auth.enabled }}
        - name: AUTHENTICATION_URL
          value: http://{{ printf "%s-auth-api" .Release.Name | trunc 63 | trimSuffix "-" }}/users/self
        {{ end }}
        volumeMounts:
        - mountPath: /usr/src/app/uploads
          name: {{ $fullName }}
      volumes:
      - name: {{ $fullName }}
        persistentVolumeClaim:
          claimName: {{ $fullName }}
