{{ $ingressEnabled := eq (include "image-storage-service.ingress.enabled" .) "true"}}
{{- if $ingressEnabled -}}
{{ $fullName := printf "%s-back" (include "image-storage-service.prefix" .) | trunc 63 | trimSuffix "-" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations: {{ include "image-storage-service.ingress.annotations" .}}
spec:
  tls:
    - hosts:
        - api.{{ include "image-storage-service.ingress.host" . }}
      secretName: {{ $fullName }}
  rules:
    - host: api.{{ include "image-storage-service.ingress.host" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: {{ $fullName }}
                port:
                  number: 80
{{- end }}
