apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "image-storage-service.api.fullname" . }}
  labels:
    {{- include "image-storage-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
