apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{include "image-storage-service.prefix" .}}-back
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
