apiVersion: v1
kind: Service
metadata:
  name: {{ include "image-storage-service.api.fullname" . }}
  labels:
    {{- include "image-storage-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "image-storage-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
