apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}-proxy
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}-proxy
    spec:
      containers:
      - name: {{ .Values.applicationName }}-proxy
        image: moreillon/api-proxy:a3e8b41e
        ports:
        - containerPort: 80
        env:
        - name: PROXY_BACK
          value: http://{{ .Values.applicationName }}-back
        - name: PROXY_ROOT
          value: http://{{ .Values.applicationName }}-gui
