apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-back
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "200Gi" .Values.pvc_sizes.imageStorage}}
