apiVersion: v2
name: time-series-storage
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v1.5.1"

icon: http://10.115.1.100:31041/images/63fd44bdfa7970e8a5c9adfe

dependencies:
  # NOTE: The official Influxdata helm chart seems to be for v1.8.x
  - name: influxdb
    version: 5.4.16
    repository: https://charts.bitnami.com/bitnami
    condition: influxdb.enabled
