apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-manager-api-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-manager-api-proxy
  template:
    metadata:
      labels:
        app: group-manager-api-proxy
    spec:
      containers:
      - name: group-manager-api-proxy
        image: moreillon/api-proxy
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
           name: environment-variables
        env:
        - name: PROXY_ROOT
          value: http://group-manager-front
        - name: IDENTIFICATION_URL
          value: ""
