apiVersion: v1
kind: Service
metadata:
  name: group-manager-api-proxy
spec:
  type: NodePort
  selector:
    app: group-manager-api-proxy
  ports:
  - port: 80
    nodePort: {{ .Values.ports.groupManager }}
