{{- $fullName := printf "%s-group-manager-proxy" (include "shinsei-manager.prefix" .) | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "shinsei-manager.labels" . | nindent 4 }}
    app: {{ $fullName }}
spec:
  type: NodePort
  selector:
    app: {{ $fullName }}
  ports:
  - port: 80
    nodePort: {{ .Values.ports.groupManager }}
